---
name: 'gitlint'
description:
  'Lints the commit messages of the branch that is currently checked out'
runs:
  using: 'composite'
  steps:
    - run: pip install yamllint
      shell: bash
    - run: ./scripts/yamllint.sh
      shell: bash
